.TH ponymix "1" "2013-01-02" "ponymix" "User Commands"
.SH NAME
ponymix \- cli volume control for PulseAudio
.SH SYNOPSIS
\fBponymix\fP [options] \fIoperation\fP [args]
.SH DESCRIPTION
\fBponymix\fP is a command line volume control for PulseAudio, letting you
perform many operations on both device and application sinks and source.
.SH OPTIONS
.PP
.IP "\fB\-c\fR, \fB\-\-card\fR \fICARD\fR"
Specify a card. By default, the card associated with the specified device
is used. Cards can be specified by name or numeric index.
.IP "\fB\-d\fR, \fB\-\-device\fR \fIDEVICE\fR"
Specify a device other than the default. Devices can be specified by name
or numeric index.
.IP "\fB\-\-max\-volume\fR \fIVALUE\fR"
Override the maximum volume ponymix will allow. This is baked in to be 100
using the \fBincrease\fR and \fBdecrease\fR methods, and 150 via
\fBset-volume\fR.
.IP "\fB\-N\fR, \fB\-\-notify\fR"
Create a libnotify notification for volume change events instead of printing
the new volume to standard output. Requires compile time support for libnotify.
Without support, this flag is a no-op.
.IP "\fB\-t\fR, \fB\-\-devtype\fR \fITYPE\fR"
Specify a device type to examine, usually in conjunction with the \fB--device\fR
flag. \fITYPE\fR must be one of \fIsink\fR, \fIsource\fR, \fIsink-input\fR, or
\fIsource-output\fR.
.IP "\fB--sink\fR, \fB--output\fR"
Aliases to \fB--devtype\fR \fIsink\fR.
.IP "\fB--source\fR, \fB--input\fR"
Aliases to \fB--devtype\fR \fIsource\fR.
.IP "\fB--source-output\fR"
Alias to \fB--devtype\fR \fIsource-output\fR.
.IP "\fB--sink-input\fR"
Alias to \fB--devtype\fR \fIsink-input\fR.
.IP "\fB--short\fR"
Generate output for list commands in a parseable format. This only applies to the
\fIlist\fR, \fIlist-cards\fR, and \fIlist-profiles\fR commands.
.SH OPERATIONS
.SS Generic Commands
.IP "\fBhelp\fR"
Display the usage and exit.
.SS Device Commands
These commands are specific to devices. Not all devices will support
all the listed commands.
.PP
.IP "\fBlist\fR"
List all available devices. This can be filtered using the \fB--devtype\fR flag.
.IP "\fBdefaults\fR"
Display the default sink and source. This is the default command if none
is specified.
.IP "\fBset-default\fR
Set a sink or source by name or numeric index as the default. The new default should
be passed using the \fB--device\fR flag.
.IP "\fBget-volume\fR"
Get the volume of a device.
.IP "\fBset-volume\fR \fIVALUE\fR"
Set the volume of a device. \fIVALUE\fR is an integer between 0 and 150.
.IP "\fBget-balance\fR"
Get the balance of a device.
.IP "\fBset-balance\fR \fIVALUE\fR"
Set the balance of a device. \fIVALUE\fR is an integer from -100 (all left) to 100
(all right).
.IP "\fBadj-balance\fR \fIVALUE\fR"
Adjust balance by the integer increment \fIVALUE\fR. The resulting balance has
the same bounds as those set by \fBset-balance\fR. The end-of-options indicator
(\fI--\fR) is required when passing a negative increment.
.IP "\fBincrease\fR \fIVALUE\fR"
Increase the volume percentage of a device or application by integer
VALUE. Increasing the volume in this way is capped at 100.
.IP "\fBdecrease\fR \fIVALUE\fR"
Decrease the volume percentage of a device by the integer \fIVALUE\fR.
Decreasing the volume in this way is capped at 0.
.IP "\fBmute\fR, \fBunmute\fR, \fBtoggle\fR"
Mute, unmute, or toggle the mute status of a device.
.IP "\fBis-muted\fR"
Check if a device is muted. ponymix will exit zero if muted, and non-zero
otherwise.
.IP "\fBis-available\fR"
Check if a device is available. This usually applies to headphone jacks, but not
all devices will support this check. ponymix will exit zero if the port is
definitively available, and non-zero if unavailable or unknown.
.SS Application Commands
These commands are specific to devices which refer to streams of applications.
For these commands, \fIsink\fR and \fIsource\fR are synonymous with \fIsink-input\fR
and \fIsource-output\fR, respectively.
.IP "\fBmove\fR \fIDEVICE\fR"
Move a device's stream to the given device, specified using the \fB--devtype\fR
and \fB--device\fR flags. Note that a source output can only be moved to
another source, and a sink input can only be moved to another sink. The type of
the target device will be inferred using this logic.
.IP "\fBkill\fR"
Kill a device's stream, specified using the  \fB--device\fR and \fB--devtype\fR
flags. This only applies to sink-inputs and source-outputs.
.SS Card Commands
These commands are specific to cards.
.PP
.IP "\fBlist-cards\fR"
List all available cards.
.IP "\fBlist-profiles\fR"
List profiles for a card.
.IP "\fBset-profile\fR" \fIPROFILE\fR
Set the specified profile for a card.
.SH AUTHORS
.nf
Dave Reisner <dreisner@archlinux.org>
Simon Gomizelj <simongmzlj@gmail.com>
.fi
.SH SEE ALSO
.BR pulseaudio (1)

